apiVersion: k3d.io/v1alpha3
kind: Simple
name: local
agents: 2
ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 9080:9080 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer