apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  url: https://istio-release.storage.googleapis.com/charts/istio/base
  interval: 60m